import { Restaurant, MenuItem, Order } from "./db";

export const mockRestaurants: Restaurant[] = [
  {
    id: 1,
    name: "Dar El Couscous",
    description: "Cuisine traditionnelle algérienne authentique",
    image: "/restaurants/dar-el-couscous.jpg",
    cuisine_type: "Algérienne",
    rating: 4.8,
    delivery_fee: 200,
    min_order: 1500,
    delivery_time: "30-45 min",
    city: "Alger",
    is_active: true,
    admin_id: 1,
  },
  {
    id: 2,
    name: "Pizza Roma",
    description: "Pizza italienne et fast food",
    image: "/restaurants/pizza-roma.jpg",
    cuisine_type: "Italienne",
    rating: 4.5,
    delivery_fee: 150,
    min_order: 1200,
    delivery_time: "25-35 min",
    city: "Oran",
    is_active: true,
    admin_id: 2,
  },
  {
    id: 3,
    name: "Tajine Palace",
    description: "Spécialités marocaines et maghrébines",
    image: "/restaurants/tajine-palace.jpg",
    cuisine_type: "Marocaine",
    rating: 4.7,
    delivery_fee: 180,
    min_order: 1800,
    delivery_time: "35-50 min",
    city: "Constantine",
    is_active: true,
    admin_id: 3,
  },
];

export const mockMenuItems: MenuItem[] = [
  // Dar El Couscous
  {
    id: 1,
    restaurant_id: 1,
    name: "Couscous Royal",
    description: "Couscous avec agneau, poulet et merguez, légumes de saison",
    price: 1800,
    image: "/menu/couscous-royal.jpg",
    category: "Plats principaux",
    is_available: true,
  },
  {
    id: 2,
    restaurant_id: 1,
    name: "Chakhchoukha",
    description: "Plat traditionnel avec galettes de pain et bouillon épicé",
    price: 1200,
    image: "/menu/chakhchoukha.jpg",
    category: "Plats principaux",
    is_available: true,
  },
  {
    id: 3,
    restaurant_id: 1,
    name: "Thé à la menthe",
    description: "Thé traditionnel algérien à la menthe fraîche",
    price: 300,
    image: "/menu/the-menthe.jpg",
    category: "Boissons",
    is_available: true,
  },
  // Pizza Roma
  {
    id: 4,
    restaurant_id: 2,
    name: "Pizza Margherita",
    description: "Sauce tomate, mozzarella, basilic frais",
    price: 1400,
    image: "/menu/pizza-margherita.jpg",
    category: "Pizzas",
    is_available: true,
  },
  {
    id: 5,
    restaurant_id: 2,
    name: "Pizza 4 Fromages",
    description: "Mozzarella, gorgonzola, parmesan, chèvre",
    price: 1800,
    image: "/menu/pizza-4-fromages.jpg",
    category: "Pizzas",
    is_available: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 1,
    client_id: 1,
    restaurant_id: 1,
    livreur_id: 1,
    status: "on_way",
    total_amount: 2300,
    delivery_fee: 200,
    delivery_address: "Rue Didouche Mourad, Alger Centre",
    phone: "0555123456",
    notes: "Appartement 3ème étage",
    created_at: new Date(),
    updated_at: new Date(),
  },
];
